### PR TITLE
[WIP] Add command line interface

### PR DESCRIPTION
**Pull request by timsurber**
This a a preview of a command line interface.

It is designed to be mostly drop-in compatible with stellar-solve (only the solving part, no annotation is planned).

Tests and reviews are welcome.

See Instructions in README

@rlancaste 
Is there a way to detect if a CPU-Timeout has happened or no index-files were found?

### CODE REVIEW

**Comment by gnthibault** [comment]
Super useful thank you !

**Comment by rlancaste** [comment]
This is a nice addition.  I have started testing this on other operating systems to verify cross platform compatibility.  I did find that some of the code you used required C++17 in order to work.  If I added set(CMAKE_CXX_STANDARD 17) in the Cmakelist.txt or set that it should use C++17 when it compiled, I was able to build it just fine on my Mac, but just building your code with the defaults, it did not work.  Would it be possible to allow building with other compiler versions or do we need the more modern features for this command line solver?  If we do need the c++17 features, then this will need to be added to either the code or the instructions.

**Comment by timsurber** [comment]
I think it would be the best choice to use C++ 2017 for the project.
Kstars also uses it and I think there is no system today which does not support a compiler for it.

And it has some useful features added.

**Comment by rlancaste** [comment]
Oh, you are right, that is near the top of KStars CMakeLists.txt.  I see that now.  Yeah, then let's do it.  I guess we will find out if that causes anyone issues.

**Comment by rlancaste** [comment]
Ok I did this.

**Pull request merged**
